moodlehq/moodle-plugin-ci

README.md
docs/CHANGELOG.md

Updating README and CHANGELOG to point to moodlehq badges, docs and issues.

Docs tweaks

---

.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/CLI.md
docs/TravisFileExplained.md
src/Command/BehatCommand.php

Embed selenium docker run in behat command.

---

.travis.dist.yml
composer.json
docs/CHANGELOG.md
docs/TravisFileExplained.md
docs/UPGRADE-2.0.md
docs/UPGRADE-3.0.md
docs/index.md

Initial preparations for version 3
Includes a brief summary of the changes to perform
and explains the order of precedence of the new nvm options
in case anybody wants to customize it (from default .nvmrc)
Also join together all the "ACTION REQUIRED" points in changelog.
And add maintainer and support information.

Initial preparations for version 3.

---

.travis.yml
README.md
docs/CHANGELOG.md
docs/ReleaseNewVersion.md

- what to change.
- how to apply those changes.
- when to tag.
- what to expect after pushing tags.
- how to proceed if the automatic "deploy" fails.

Complete the release docs with some important details

---

.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/TravisFileExplained.md

It's a new Moodle 3.10 requirement, see MDL-67415 for more info.

Bump to PostgreSQL 9.6

---

composer.json
composer.lock
docs/CHANGELOG.md

Hello @sarjona,
This is an update to use the latest version of local_codechecker.

Prepare for 3.0.3 release

---

docs/ReleaseNewVersion.md

Move a note in the 'Release new version' page to earlier in the doc

---

.github/workflows/test.yml
.travis.yml
Makefile

This patch contains GitHub actions for push and pull-requests to master branch.
Addressing #54 ("release" action will be in separate PR)

GitHub actions for push and pull-requests

---

.github/workflows/test.yml

This is a flag to be able to manually trigger test when needed:

Add workflow dispatch event.

---

Makefile
composer.json
composer.lock
docs/CHANGELOG.md
psalm.xml
src/Bridge/Moodle.php
src/Command/AddPluginCommand.php
src/Command/CoverallsUploadCommand.php
src/Parser/StatementFilter.php
src/PluginValidate/Finder/TableFinder.php

Not much to say, just bump to current ones to verify they pass and to have the latest fixes applied.

Bump to current local_ci and local_moodlecheck

---

docs/CHANGELOG.md
src/Command/BehatCommand.php

I'm pretty sure that this is correct but I don't know how best to test it.
This will be required for MDL-66979

Use legacy Firefox for legacy php-webdriver

---

docs/CHANGELOG.md

Part of the release process: https://moodlehq.github.io/moodle-plugin-ci/ReleaseNewVersion.html

Prepare for 3.0.5 release

---

composer.json
composer.lock

This comes with https://github.com/moodlehq/moodle-local_moodlecheck/pull/69 and, also, together, switched to composer 2 to generate the lock file.

Bump local_moodlecheck and switch to composer2

---

docs/GHAFileExplained.md
docs/IgnoringFiles.md

Following on from https://github.com/moodlehq/moodle-plugin-ci/issues/104 and https://github.com/moodlehq/moodle-plugin-ci/issues/107 - I've improved the documentation and fixed the example in IgnoringFiles.md as it was a duplicate of the global example.

Improve ignore documentation.

---

.github/workflows/test.yml
src/Command/InstallCommand.php

Hi @kabalin 
Just created a new branch, as the branch name is misleading.
This PR is based on #106 
Greets
Adrian

Add optional CI_BUILD_DIR environment variable

---

docs/IgnoringFiles.md

Rendered change: https://github.com/kabalin/moodle-plugin-ci/blob/ignore-doc/docs/IgnoringFiles.md

docs: Add file ignoring configuration example for GHA.

---

src/Command/BehatCommand.php

Temporarily avoid issues with later release, fixes #121.

Pin Selenium to known working version.

---

docs/CHANGELOG.md

This quick release is addressing selenium issue. Follow up issue to revert change at later point: #123 
Also, as this is release PR, please, remember that "when merging PR, please avoid merge commit (use "Rebase and merge" option)".

Prepare for 3.2.1 release

---

src/Command/BehatCommand.php

This reverts commit 948c74f3fca2efa4326bde238bde40fcbead436d.
Fixes #123

Revert "Pin Selenium to known working version."

---

src/Command/BehatCommand.php

Aligning with version tested in moodlehq/moodle-docker#195

Unpin Selenium version for Firefox

---

src/Command/BehatCommand.php

As we already use host networking. Fixes #147

Don't publish port at selenium container

---

composer.json
composer.lock
tests/Fixture/moodle-local_ci/classes/math.php
tests/Fixture/moodle-local_ci/db/upgrade.php
tests/Fixture/moodle-local_ci/lib.php
tests/Process/ExecuteTest.php

Amending the tests to the new Sniffs available. Plus adding a note
to the ExecuteTest.php because it generates output to php logs and
always confuses me, looking why it's happening.

Bump to codechecker v3.0.5

---

docs/CHANGELOG.md

Adjusting the CHANGELOG for release.
Remember this has to be applied via "Rebase and merge" (without merge commit).
Ciao :-)

Prepare for 3.2.3 release

---

composer.json
composer.lock

This just bumps to new codechecker release that incorporates this fix:
https://github.com/moodlehq/moodle-local_codechecker/pull/174
Ciao :-)

Bump to codechecker v3.0.6

---

docs/CHANGELOG.md

This needs to be incorporated without merge commit, aka, using "Rebase and merge".
Ciao :-)

Prepare for 3.2.4 release

---

.github/workflows/test.yml
.travis.yml

Not much to say, just ensure we are testing agains 400_STABLE.

Add 400_STABLE to CI tests

---

composer.json
composer.lock
docs/CHANGELOG.md

Not much to say, just ensure we are running the latest:
- local_ci
- local_moodlecheck

Update tools to current ones

---

docs/CHANGELOG.md

Fix Changelog year 3.4.4

---

docs/TravisFileExplained.md

fix composer package name in `composer create-project`

fix composer package name

---

src/PluginValidate/Requirements/ModuleRequirements.php

ModuleRequirements: add mod_form.php

---

docs/ReleaseNewVersion.md

docs: Add dependencies update recommendation to ReleaseNewVersion.

---

composer.json
composer.lock
docs/CHANGELOG.md
src/Bridge/Moodle.php
src/Command/BehatCommand.php
src/Command/MustacheCommand.php
src/Command/PHPDocCommand.php
src/Installer/TestSuiteInstaller.php

Address Moodle code directories restructure [MDL-83424](https://tracker.moodle.org/browse/MDL-83424).
Passes at [test branch](https://github.com/kabalin/moodle-plugin-ci/tree/MDL-83424-test), see https://github.com/kabalin/moodle-plugin-ci/actions/runs/16114791619
[MDL-83424]: https://moodle.atlassian.net/browse/MDL-83424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support new directory structure
