src/Command/BehatCommand.php

On multiple jobs parallel run, depending on Travis resources allocation,
starting docker container can easily exceed default 60 seconds.
Example: https://travis-ci.org/github/kabalin/moodle-plugin-ci/jobs/709359114 (from build https://travis-ci.org/github/kabalin/moodle-plugin-ci/builds/709359109)

Disable timeout for Docker run process.

---

.travis.yml
composer.json
composer.lock
docs/CHANGELOG.md

This bumps codechecker to just released v2.9.7.
Also, sets php min version to 7.0.0 and update some components:
- php-parallel-lint
- PHP-Console-Highlighter
(so both will use new php-parallel-lint vendor)
Also updated:
- moodle-local_ci to current upstream version.
- moodle-local_moodlecheck to current upstream version.
Then regenerate composer.lock with php 7.0.
Finally, bump own travis to use highest php version in each branch (and also lowest in oldest branch).

Codechecker 297 and co

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/InstallCommand.php
src/Installer/InstallerFactory.php
src/Installer/VendorInstaller.php
tests/Installer/VendorInstallerTest.php

The option allows to override default Node.js version (which is picked
from .nvmrc) by providing --node-version parameter or defining
`NODE_VERSION` env variable. The value of this parameter should be
compatible with `nvm install` command, e.g. `v8.9`, `8.9.0`,
`lts/erbium`. Basically, assume it is added to .nvmrc and nvm should be
able to consume it while running `nvm install && nvm use`.

Add --node-version parameter to install step.

---

.travis.yml

This just adds one more job (310) in the integration tests,
adding it to the list of correctly processed grunt branches
(together with 39 and master).
Once we get 35, 37, 38 out of support we'll be able to remove
that exceptional exit code handling (that I've not verified,
to be honest).
This fixes #29.

Add 310 to own tests

---

composer.json
composer.lock
docs/CHANGELOG.md

The travis-ci is still using the old version of the local_moodlecheck plugin. As a result, I am seeing some false failures such as "Invalid inline phpdocs tag @see found" which I am not getting when using the latest version locally.
I suspect that the commit c006b90ac2283fed1975f7039ab9cc40c75bdf0c only raised the "version". But that does not really do anything imho without setting the "reference" hash correctly.

Fix the commit reference of the latest local_moodlecheck plugin

---

composer.json
composer.lock
docs/CHANGELOG.md

Just bumping to current local_ci and local_moodlecheck that
come with some nice improvements:
- Support .mustachelintignore in mustache linting.
- Better valid API detection (online and external).
- Anonymous classes false positives.
Only the 1st one is worth being shared in the CHANGELOG, because it's something that devs can now go adding to their plugins, instead of using IGNOREFILES to completely ignore those files.
Note that this PR, if accepted must be applied WITHOUT commit merge ("rebase and merge", usually), because will be tagging it as 3.0.2.

Prepare for 3.0.2 release

---

docs/ReleaseNewVersion.md

While it's also possible to use GH release interface
it's better to avoid using it. Just tag manually, send
the tag upstream and travis will both:
1) Create the needed release artifacts (moodle-plugin-ci.phar)
2) Perform the official release.

Let's always use manual tagging and push upstream

---

composer.json
composer.lock
psalm-baseline.xml

That makes a number of components to be also updated to 3.4.x
and requires php >7.0.8 (instead of 7.0.0).
Also updated psalm-baseline.xml to ignore 'node-version' potential
wrong assignment values.
Note I've not run `--update-baseline` because it comes with other
changes that I don't want to modify now (removing some options).
I leave that for the experts because I'm not sure how the baseline
is decided and which part is automatic or manual.
A step before #21

Bump symfony dep injection component to ^3.4

---

README.md
docs/index.md

More info available @ https://tracker.moodle.org/browse/MDLSITE-6246
Note that moodlehq/moodle-plugin-ci (this repo), already has been moved to travis-ci.com as part of the issue above. This PR just updates links to point to new place.

Migrate from travis-ci.org to travis-ci.com

---

docs/CHANGELOG.md
src/Command/PHPUnitCommand.php

This is to prevent memory exhausted error when test coverage is
requested (reflecting dc46266419).

PHPUnitCommand: Disable memory limit for phpdbg run

---

src/Installer/VendorInstaller.php

This is necessary (or at least helpful) for running on github actions.
It also seems like a good idea generally, to make thing more self-contained.
I have not tested to see if this is OK on Travis, but I assume it is.

Don't install grunt globally. Instead run it with npx

---

README.md

This is how it looks rendered: https://github.com/kabalin/moodle-plugin-ci/tree/badge

Add GitHub actions badge to README

---

.github/workflows/release.yml
.github/workflows/test.yml
.travis.yml
docs/ReleaseNewVersion.md

This patch is migrating automated release step from travis to GitHub Actions.
**To see how patch work:**
Test release 3.0.3.1: https://github.com/kabalin/moodle-plugin-ci/releases
Relevant release action: https://github.com/kabalin/moodle-plugin-ci/actions/runs/436555868
Following the merge:

Add GitHub Action for release.

---

.github/workflows/release.yml
.github/workflows/test.yml
Makefile

This also makes changes:
* `make test-phpunit` is removed from GHA workflow (already run as part of `make validate`)
* Use ubuntu 16.04 so we have phpdbg 7.0 available (needed for 3.5)
* Add verbosity.
* Makefile changes: running `make init` is required before running any test/validate command.

Re-add coverage param to phpunit test

---

.github/workflows/test.yml

By the look of it, `nvm` is included in ubuntu environments (e.g. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md). Not sure how it was overlooked 🤷‍♂️

GHA: nvm is available.

---

README.md
docs/CHANGELOG.md
docs/GHAFileExplained.md
docs/Help.md
docs/ReleaseNewVersion.md
docs/index.md
gha.dist.yml

Based on examples in #48 which were carefully reviewed and used in [moodle-mod_coursecertificate](https://github.com/moodleworkplace/moodle-mod_coursecertificate/blob/master/.github/workflows/moodle-ci.yml). Many thanks to @timhunt, @mackensen, @marinaglancy and others involved in discussion in related tickets.

Add GitHub Actions example and docs.

---

.github/workflows/test.yml

The most important it the push one, because anybody
contributing to mooodle-plugin-ci wont get their
dev/proposal branches tested. Only if they work on
master, they will.
About pull requests, this is less critical, as far as
master is out only current branch. But tomorrow we may
rename it, or create new upstream branches, so there
isn't anything wrong opening the doors to that now.

Enable all branches, both for push and pull requests

---

docs/CHANGELOG.md
src/Command/GruntCommand.php

It looks like we relied on system installed one so far in grunt task (see https://github.com/kabalin/moodle-plugin-ci/runs/1845524756?check_suite_focus=true#step:7:53 modified run that included `whereis grunt`):
Something I forgot to check when #51 was landed 😞 Only noticed as I tested the latest `moodle-plugin-ci` within `moodlehq/moodle-php-apache:7.2` based container in Gitlab and it failed with `sh: 1: grunt: not found`.

Run grunt task using npx.

---

.php-cs-fixer.php
Makefile
bin/moodle-plugin-ci
tests/Command/SavePointsCommandTest.php

That version supports PHP8 and is the last one
before jumping to v3 that comes with huge changes.
This will help in the progress towards PHP8 support happening @ #94

Bump php-cs-fixer to v2.19.0

---

composer.json
composer.lock
psalm-baseline.xml
src/Bridge/MessDetectorRenderer.php
src/Command/MessDetectorCommand.php
src/Parser/StatementFilter.php
src/PluginValidate/Finder/FunctionFinder.php

Most noticeble one being local_moodlecheck v1.0.7 that
comes with PHP8 specific fixes.
Also updated nikic/php-parser to newer version, able
to run with any >= 7.0 PHP version (8.0 included) and
parse every PHP version (5.x to 8.0).
Changes to the php-parser required some changes in code:
- Look for assignments inside extra Expression element.
- Add 3 psalm cases to baseline, about some casts (the
objects have the _toString() method, but psalm isn't
aware).
(details @ https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-4.0.md)
Finally, some changes because of phpmd bump were also required.

Update project dependencies

---

composer.json
composer.lock

No much to say, this could have happened in the previous PR, when we also switched to tagged `local_moodlecheck`, but there were other impeding changes there.
So doing it here, now local_ci has tags too, so using them.
Ciao :-)

Move local_ci dependency to tagged one

---

.travis.dist.yml
docs/CHANGELOG.md
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml

Bumped to 3.1, because of the needed changes to get PHP 8 working.
Following https://moodlehq.github.io/moodle-plugin-ci/ReleaseNewVersion.html instructions
This must be incorporated without merge commit, for better tagging target.
Feel free to discuss any detail, I'm not the best writing this stuff!

Prepare for 3.1.0 release

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml

Basically:
- postgres min version bumped to 10 (from previous 9.6).
- exif php extension is now recommended.
For more info: https://tracker.moodle.org/browse/MDL-70594
This commit changes, all-together:
- Own GHA and Travis tests.
- GHA and Travis templates.
- Documentation and Changelog.

Bump to fulfill 4.0 requirements

---

docs/CHANGELOG.md
docs/GHAFileExplained.md
gha.dist.yml

New mariadb:10.6 makes the COMPRESSED row format read-only by default
because it's deprecated now and will be removed in mariadb:10.7
This is being tracked @ https://tracker.moodle.org/browse/MDL-72131
Once that issue is fixed and we switch to DYNAMIC or whichever the
final solution is, we'll unpin this.

Make mariadb:10.5 sticky

---

.github/workflows/test.yml

And being removed from the GHA setup-php
https://github.com/shivammathur/setup-php
https://github.com/shivammathur/setup-php/issues/452
So, jumping to 20.04 ~and also adding some mising php80 runs.~

Remove ubuntu 16.04 from self-tests, out of support

---

docs/CLI.md
docs/GHAFileExplained.md
docs/TravisFileExplained.md
src/Command/InstallCommand.php

Mentioned at https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
I believe as I write this GitHub is in the midst of the first scheduled brown-out.

GitHub no longer supports the git:// protocol

---

docs/CHANGELOG.md
src/Bridge/MoodlePlugin.php
src/Bridge/MoodlePluginCollection.php
tests/Bridge/MoodlePluginCollectionTest.php
tests/Bridge/MoodlePluginTest.php
tests/Fake/Bridge/DummyMoodlePlugin.php

The current implementation of the install command doesn't work as expected where the extra-plugins directory contains a plugin and a subplugin of that plugin. There is an implied dependency between the subplugin and the parent plugin which isn't accounted for, so the subplugin may be installed first, giving the following error:
> In Moodle.php line 113:                       
> The component metadatafieldtype_file has an unknown plugin type of metadatafieldtype
This can be reproduced by cloning the [local_metadata](https://github.com/PoetOS/moodle-local_metadata) plugin into the extra-plugins directory, and then moving the directories within the fieldtypes directory (which are subplugins) up to the root of the extra-plugins directory.

Support subplugins in install

---

.php-cs-fixer.php
src/Installer/TestSuiteInstaller.php
tests/Fake/Bridge/DummyMoodle311.php
tests/Fixture/phpunit/coverage.php
tests/Fixture/phpunit/phpunit-311.xml
tests/Fixture/phpunit/phpunit-expected-311.xml
tests/Installer/TestSuiteInstallerTest.php

This has to be considered / merged after #139 (it's built on top of it).
Revamped phpunit code coverage analysis
- Whenever a tests/coverage.php file is filter, don't apply
code coverage defaults any more. That file is used by phpunit
init to properly configure the desired coverage. This rule
only applies when running tests against Moodle 3.7 and up.
- Whenever we are using PHPUnit 9.5 and up, use the new coverage
syntax where <filter><whitelist> became <coverage><include>. This
rule only applies when running tests against Moodle 3.11 and up.
- Covered with tests.
Closes #93 and #120
Also:
Remove the 'header_comment' rule from php-cs-fixer
It was enforcing us to keep the Blackboard header for all files
when new ones shouldn't be subject to that copyright notice.

Coverage php has precedence

---

composer.json
composer.lock
docs/CHANGELOG.md
tests/Fixture/moodle-local_ci/tests/lib_test.php

This needs to be merged after #141 
This bumps local ci/moodlecheck/codechecker to the latest
released / tags created last week.
Also fixes a test caused by recent changes.
Finally, unrelated with this, add to the CHANGELOG all the
changes, still missing to be documented there, since last
release of moodle-plugin-ci

Bump sub-tools to latest releases

---

.github/workflows/test.yml

We already were doing that in self (ci) tests and
also in recommended gha.dist.yml for plugins.
But for some reason (miss I imagine) we left this
validate test still installing both xdebug and then
using phpdbg for collecting coverage information.
And, as of today, it has started to crash (curiously,
it was not crashing earlier):
https://github.com/moodlehq/moodle-plugin-ci/actions/runs/1572798313
So, doing things properly, just disable any other covergae
extension because we use phpdbg.

Disable xdebug and pcov from self (validate) tests

---

docs/CHANGELOG.md

Following the [Releasing a new version](https://moodlehq.github.io/moodle-plugin-ci/ReleaseNewVersion.html) process.
Remember that we need to incorporate this avoiding the "Merge" option. Instead, use "Rebase and merge”.
Ciao :-)

Prepare for 3.2.2 release

---

.github/workflows/release.yml

Before this, forks getting the tags pushed were performing
own releases of moodle-plugin-ci. Let's run that job only
for the root "moodlehq" one.
You can see, for example, my "stronk7" fork, all releases
have happened also there:
https://github.com/stronk7/moodle-plugin-ci/releases
Ok, it seems to be working as expected:
1. I've created the 6.6.6 tag for the `no_release_on_forks` branch (that has the new condition), pushed it to my "stronk7" fork and only the "Moodle Plugin CI" workflow has been launched. The "Create Release" one is dimmed.
2. I've created the 7.7.7 tag for the `master` branch (that doesn't have the new condition), pushed it to my "stronk7" fork and both the  "Moodle Plugin CI" and the  "Create Release" workflows have been launched.
3. So, only the [7.7.7 release has been …

Avoid forks to perform releases when they receive tags

---

docs/CHANGELOG.md
docs/GHAFileExplained.md
gha.dist.yml

Now that 10.6.7 and 10.7.3 have been releases and their
docker images are available, we can unpin it @ GHA.
Fixes #116

Unpin MariaDB

---

gha.dist.yml
src/Installer/Database/MySQLDatabase.php
tests/Installer/Database/MariaDBDatabaseTest.php
tests/Installer/Database/MySQLDatabaseTest.php

Moodle 4.0 contains language strings that need the full 4 bytes UTF-8 code. So the MySQL and MariaDB moodle-plugin-ci databases should also support full unicode (issue #37).

Use utf8mb4 for mysql and mariadb

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/CLI.md
gha.dist.yml
src/Command/PHPUnitCommand.php
tests/Fixture/moodle-local_ci/tests/lib_test.php

When there are warnings in the phpunit results the exit code is 0.
The typical warning we receive is incorrect "@covers" tag. The pipeline does not fail but the output shows that there are warnings:
```
$ . check moodle-plugin-ci phpunit --coverage-text
RUN  PHPUnit tests for tool_tenant
Moodle 4.0 (Build: 20220419), b10a543752f72d95987b8672ecf0a1348cdc9bac
Php: 7.3.33, pgsql: 10.20 (Debian 10.20-1.pgdg90+1), OS: Linux 4.4.0-1052-aws x86_64
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.
..........S.S.......................................WWWWW......  63 / 191 ( 32%)
........................................SSSSSSS................ 126 / 191 ( 65%)
.....................................................WWWWWWWWWW 189 / 191 ( 98%)
WW …
```

PHPUnit should fail if there are warnings

---

docs/CHANGELOG.md
src/Installer/VendorInstaller.php

moodle-plugin-ci is not ready for this yet. We need to move
from current use of local_codechecker to composer + moodle-cs
before being able to allow these new .phpcs.xml files in core.
So, for now, we are just deleting it as part of the tool
installation. This will be revisited when moving to the
new approach commented above.

Remove .phpcs.xml files immediately after creating it

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
Makefile
docs/CHANGELOG.md
docs/CodeCoverage.md
docs/GHAFileExplained.md
gha.dist.yml
src/Command/PHPUnitCommand.php

Right now we are only using phpdbg for phpunit code coverage. And
it's causing some problems with latest (8.0, 8.1) php versions.
Also, since phpunit 8, its code coverage tool supports pcov, that
is the lighter and better alternative. And then, xdebug running
in coverage mode has become way better in recent versions.
So, with this patch applied, moodle-plugin-ci will look for the
"best" code coverage alternative (pcov => xdebug => phpdbg) in
every run.
This guarantees that existing automations, not having pcov or
xdebug available will continue fall-backing to phpdbg. But if
any of the 2 extensions are available, we'll be using them.
No matter of the above (fully automatic), it's also possible
to configure the desired code coverage tool with 3 new options,
in case it's needed to force any: …

Use pcov => xdebug => phpdbg for phpunit code coverage

---

composer.json
composer.lock
docs/CHANGELOG.md
src/Command/CodeCheckerCommand.php
src/Command/CodeFixerCommand.php
src/Installer/VendorInstaller.php
src/StandardResolver.php
tests/Command/CodeCheckerCommandTest.php
tests/Command/CodeFixerCommandTest.php

In summary, this makes moodle-plugin-ci to stop using local_codechecker as a requirement and starts using the, now split, moodle-cs standard (with both it and PHP_CodeSniffer being installed via composer).
That was, any new sniff added to the standard and released, or any new PHP_Codesniffer version will be used immediately, without having to make "fake" local_codechecker releases anymore.
Note this PR has 2 commits:
1. The first just does the switch but continues using PHP_Codesniffer as a library, within PHP like it was an API. This API use was causing some problems, specially like #167, affecting all current versions (both before and after the commit).
2. The second commit makes the change from library to binary so, now, we use the `phpcs` binary passing everything from CLI / shell …

Move to moodle cs

---

.php-cs-fixer.php
Makefile
bin/moodle-plugin-ci
bin/validate-version
composer.json
composer.lock
docs/CHANGELOG.md
docs/ReleaseNewVersion.md

IMPORTANT: This needs to be merged after #171 is merged and this has been rebased (composer regenerated).
With this change:
1. moodle-plugin-ci.phar will continue working the same,
with `--version` always returning the correct (git describe)
version used to build the phar.
2. bin/moodle-plugin-ci will also show the correct (git describe)
version, when it's run from a git directory. If not git is detected
the version specified in `$version` will be used.
Plus:
- In order to ensure that the `$version` is updated on every release a
new check has been added to `make validate`. It will compare the
latest version documented in the 'docs/CHANGELOG.md' file with the
version in the `bin/moodle-plugin-ci` file.
- Release docs have been amended to remember to update the version
in …

Changes to guarantee that --version works always

---

docs/CHANGELOG.md
docs/CLI.md
psalm-baseline.xml
res/template/config.php.txt
src/Bridge/MoodleConfig.php
src/Command/InstallCommand.php
src/Installer/Database/AbstractDatabase.php
src/Installer/Database/DatabaseResolver.php
src/Installer/Database/MySQLDatabase.php
src/Installer/Database/PostgresDatabase.php
tests/Fixture/example-config.php
tests/Installer/Database/DatabaseResolverTest.php

Add support for non-default database ports. For example, you cannot run a MariaDB and MySQL database on the same host with the default ports.

Add --db-port option

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml
src/Installer/Database/PostgresDatabase.php

Trivial for GHA, just change of images to postgres:12, but...
Travis changed the PostgreSQL package for version 11 and up so, instead of
using the "postgres" user it now uses the "travis" one. And the port is
5433 instead of 5432. We use the existence of the PGVER environmental
variable to decide which defaults to use.
More yet, the connection via "localhost" (local net) now requires login and
password, it used to be trust/peer auth mode (not requiring password). If we want to
keep localhost (+ port) working, then we need to edit the  pg_hba.conf file
to trust/peer the local connections and then restart the database.
So, at the end, we are going to use socket connections (host = '')
that is perfectly ok for Travis (non dockered database). Only if they
haven't been configured another way …

Bump self-tests to 4.1 requirements

---

.github/workflows/release.yml
.github/workflows/test.yml
docs/CHANGELOG.md
docs/GHAFileExplained.md
gha.dist.yml

Since some time ago, GH is warning us that the Ubuntu 18.04 environment is deprecated:
"The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead...."
Hence, we are bumping here, to be able to cerify if everything continues working ok.
The changes cover own scripts, templates and guides. All them now pointing to Ubuntu 22.04 (jammy).

Bump GHA environments to use Ubuntu 22.04

---

.github/workflows/release.yml
docs/CHANGELOG.md

Old ones have been archived, so moving away from them. The picked one ([ncipollo/release-action](https://github.com/ncipollo/release-action))seems to be well supported, it has not many issues or prs pending and includes new stuff like node16 support.
I've created a couple of releases in my fork, and, apparently, everything has worked perfectly, with the release being created, the changes body working and the phar asset becoming available.
https://github.com/stronk7/moodle-plugin-ci/releases
Fixes #189.

Switch to ncipollo/release-action

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml

Note we also have applied a couple of extra changes:
- Rename the both travis and gha job names to match.
- Refactor travis noticeably to better separarte validate
and integration tests, avoiding the "phantom" job that
was caused by the matrix behaviour.

Bump CI tests to use PHP 8.0 and PostgreSQL 13

---

composer.json
composer.lock
docs/CHANGELOG.md
tests/Command/CodeCheckerCommandTest.php

Since moodle-cs 3.3.0 we are using "phpcompatibility/php-compatibility": "dev-develop#2fb82334" because the last version released (3.9.5) is from 2019 and missing lots of stuff and, also, compatibility with php81 and up.
To be able to install those new moodle-cs versions, all products installing it must explicitly require that php-compatibility version.
Once the make a new release, we'll be able to revert this.

Force php-compatibility dev to be used

---

docs/CHANGELOG.md
docs/CodeCoverage.md
src/Command/CoverallsUploadCommand.php

The old satooshi/php-coverall v1 has stopper working recently, so bumping to v2.
Also, make the installation of it optional, better for local environments where it can be already installed.
Fixes #59

Bump to php-coveralls/php-coveralls v2

---

composer.json
composer.lock
docs/CHANGELOG.md

- local_ci
- local_moodlecheck
Not much to say, just updating before making a quick release. The updates will solve a few composer warnings, espcially when installing the local_ci requirements, because there was a wrongly named file leading to this warning:
```
Class MoodleHQ\MoodleCS\moodle\Tests\MoodleCsStandardTest located in ./vendor/moodlehq/moodle-cs/moodle/Tests/MoodleStandardTest.php does not comply with psr-4 autoloading standard. Skipping.
```
Not the end of the world, because that Test file is not used (comes from moodle-cs), but towards a clean composer install.
Ciao :-)

Update tools to current ones

---

.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/TravisFileExplained.md
src/Installer/Database/PostgresDatabase.php

NodeJS 18 requires GLIBC 2.28, that only comes in 18.10 (non LTS) and 20.04 (focal) Ubuntu versions. Change all the Travis references to point to that, because, by default, it uses denial older version.
Also bump the "make validate" self tests and the Travis dist files and docs to use php74 as minimum,,
because focal on Travis doesn't support php73 any more.
Finally, it seems that, for focal, they have changed again the PostgreSQL port to be 5432 (it was 5433 for PostgreSQL 11 and 12). So let's specify it again. Ping, pong!
Side note: We have disabled grunt for all Moodle 3.x branches because the Node 18 issue came with unexpected changes to .map files and now they are failing. [MDL-77527](https://tracker.moodle.org/browse/MDL-77527) has been created to fix that regression of …

Bump all travis files and docs to require Ubuntu 20.04

---

src/Command/CodeCheckerCommand.php
tests/Command/CodeCheckerCommandTest.php

After reading through the PHPCompatibility documentation, it seems that without setting the testVersion value, we are not getting the errors for backward-incompatible functionality. Specifically, functions, constants, syntaxes and classes that were added in newer versions were not being reported. It was only reporting forward-incompatible changes (functionality that had been removed in newer versions of PHP).
Fixes #205

Support PHPCompatibility testVersion config

---

.github/workflows/release.yml
docs/CHANGELOG.md

Using the yashanand1910/standard-release-notes action, now we are extracting the matching version from the docs/CHANGELOG.md file and adding it to the release notes.
This is an example of a released version (99.99.99) and how the release info looks:
https://github.com/stronk7/moodle-plugin-ci/releases/tag/99.99.99
And, this an example of a failed run because the released version (99.99.98) does not have any entry in the changelog:
https://github.com/stronk7/moodle-plugin-ci/actions/runs/4347058191
Ciao :-)

Automatically add the version changelog section to the release notes

---

.travis.dist.yml
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml

These comment changes include the additional context that I was previously missing to understand how code coverage works in moodle-plugin-ci.
Also, switches the examples to use `phpcs` instead of the `codechecker` alias.
Fixes #211 (deprecating phpdbg should probably be a separate issue)

CI Example Updates

---

.travis.dist.yml
docs/CHANGELOG.md
docs/CLI.md
docs/GHAFileExplained.md
docs/Help.md
docs/TravisFileExplained.md
gha.dist.yml
src/Command/PHPDocCommand.php
tests/Command/PHPDocCommandTest.php
tests/Fake/Bridge/DummyMoodlePHPDoc.php
tests/Fake/Process/DummyExecute.php

To be on pair with the PHPCs command, now we support the same option (`--max-warnings xx`) within PHPDocs.
Now, by defaults, warnings will be allowed (previously they were leading to exit with error). And if anybody wants to be stricter, adding `--max-warnings 0` will do the trick. (or any other number if there are a number of warnings to allow).
Covered with (dummy) tests, because the execution of the PHPDoc command requires a complete moodle checkout.
Fixes #186
Note that, before this is merged, these requirements are needed:
So, please, **don't merge this until the 3 requirements above are ticked**. Of course, you're welcome to review it, any time!

Add --max-warnings option to the PHPDoc command

---

.github/workflows/test.yml
.travis.yml

With the PHP 8.2 epic (https://tracker.moodle.org/browse/MDL-76405) near being completed, it's time to verify and continuously test that everything is passing with that PHP version.

Bump 402 and master tests from php81 to php82

---

.github/workflows/release.yml
Makefile
box.json
docs/CHANGELOG.md

Current version (2.x) is really old and emitting some warnings with php >= 8.1. So, just move to current 4.x version.
Simply change to its new incarnation (fork of the original) and tidy up a few parameters.
Note that the phar still has a good number of limitations:
- Not all checks work (phpcs, behat...).
- Cannot post-install moodle-local_ci (vnu.jar)
- ...
But all those are pre-existing and this new version does not change that.
Note that box requires PHP 8.1 to build the phar, but the phar works perfectly with PHP 7.4 (our min requirement).
Fixes #235

Update to current box version (phar packaging)

---

box.json
docs/CHANGELOG.md
src/Command/MustacheCommand.php

We need both the php script and the bundled vnu.jar files to be put in tmp dir and execute/use them from there.
This shouldn't affect normal (non-phar executions). Note that tests cover the non-phar case.

Enable mustache check to run from phar

---

box.json
docs/CHANGELOG.md
src/Command/CodeCheckerCommand.php
src/Command/CodeFixerCommand.php

Note this is very similar to #237 (that **should be merged before this**).
We need the 2 CLI scripts and the CodeSniffer.conf file to be added to the phar, so we can "include" the scripts for execution and copy the conf file temporarily to be together with the phar (that's the way CodeSniffer expects it).
Note this will reduce a little bit code-coverage but in a future PR I want to add some integration tests to cover the execution from phar, hardly can be done from unit tests.

Enable phpcs and phpcbf checks to run from phar

---

.travis.yml

To be done after #239
While we still keep moodle-plugin-ci officially supported with Travis, it just so slow (for our current paid plan) that make any branch or PR to take ages to be tested (~1 hour).
So here we are reducing the number of branches being tested to:
- master (highest PHP version supported).
- latest stable (highest PHP version supported).
- oldest stable supported (lowest PHP version supported).
That will save some precious minutes (7-8 per run) making things a little bit more agile, specially given the falling relevance of Travis since a couple of years ago (compared with the raise of GHA).

Remove CI testing on Travis

---

.github/workflows/test.yml
docs/CHANGELOG.md

Over the last days, we have fixed a number of checks to work ok when using the `moodle-plugin-ci.phar` alternative.
Obviously, that's not covered with unit tests, so we need to add some integration tests, similar to the `bin/moodle-plugin-ci` ones, but using the PHAR instead.
Here they are, we test them once for each PHP version supported, that should be enough.
Plus, we make the PHAR available as artifact in the GHA runs so people can download them from there (normally we only rebuild the PHAR for releases).
Ciao :-)

Add phar integration tests

---

.gitattributes

We had not updated this file since long ago and there are some new/moved paths to get excluded from distribution when installed as a dependency.

Update .gitattributes to current files to keep out from packages

---

composer.json
composer.lock
src/Command/SelfUpdateCommand.php

The self update command dependencies were removed in the past but the command was left around. As a result of that any attempt of running:
`php moodle-plugin-ci.phar selfupdate`
Is failing with PHP error (because the underlying humbug/phar-updater library was not available any more.
So, with this commit, we are re-introducing it, but with the following observations:
1. We have moved from humbug/phar-updater (archived) to laravel-zero/phar-updater that is maintained.
2. We are stuck to version 1.*, because of we still supporting PHP 7.4
3. I've run it with PHP 8.2 and it doesn't break badly, just some PHP deprecated notices are displayed. In any case, far better than the previous status, not working at all.
4. Having it back to code will allow us to further progress:
- Getting it tested …

Add back the selfupdate command (interim mode)

---

docs/CHANGELOG.md
docs/CodeCoverage.md
docs/GHAFileExplained.md
gha.dist.yml

As described in #248, GitHub discourages the use of always() when it can be avoided.
Fixes #248

ci examples: use !cancelled() instead of always()

---

.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/TravisFileExplained.md

For some strange reason, travis has started to fail with PHP 8.2 with error:
php: error while loading shared libraries: libonig.so.5
It was not happening few days ago. Searching out there it seems that the fix is as simple as apt-installing that library.
It's incredible that they don't have that implemented in their environments and things like this need to be installed manually.
Any way, fixed in our own Travis test and also in the template and docs.

Add the libonig5 to the Travis packages to install

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/BehatCommand.php
src/Command/PHPUnitCommand.php
tests/Command/BehatCommandTest.php
tests/Command/PHPUnitCommandTest.php
tests/Fake/Process/DummyExecute.php
tests/MoodleTestCase.php

This PR has 3 commits:
1. Modify `DummyExecute` in order to make the last command executed available for testing purposes.
2. Add the `--tags` and `--name` Behat options available (#246).
3. Add the `--configure`, `--testsuite` and `--fillter` PHPUnit options available (#100).
I've added 2 `TODOs` in the code about some tests that, IMO, are wrong. They are pre-existing and won't be analysed or fixed here.
Ciao :-)

New behat phpunit options

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/CodeCheckerCommand.php
tests/Command/CodeCheckerCommandTest.php

I've been trying to exclude some rules from a plugin using a `.phpcs.xml` file and I didn't manage to do it. But it was very easy using [the exclude option](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#limiting-results-to-specific-sniffs). I think this would be a nice addition.

Implement --exclude option in phpcs command

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/CodeCheckerCommand.php
tests/Command/CodeCheckerCommandTest.php
tests/Fixture/moodle-local_ci/lib.php

A new `todo-comment-regex` option has been added to the phpcs command.
It allows to specify the regex that will be used with inspecting
todo (TODO and @todo) comments.
By default, an empty string is used for the option and that makes
the Sniff to stop checking. Whoever wants to check for anything
(tracker issue, github issue, arbitrary url, ...) can us the new
option to configure it.
Fixes #266

Prevent plugin runs to use the moodle.Commenting.TodoComment sniff

---

docs/CHANGELOG.md
docs/CLI.md
docs/GHAFileExplained.md
docs/Help.md
docs/TravisFileExplained.md
docs/index.md
phpunit.xml.dist
src/Command/CopyPasteDetectorCommand.php

deprecation as a stepping stone towards full removal. 
i tried to be cheeky by triggering a deprecation error when the command is executed, but that didn't pan out. 
so it's all documentation, and one `@deprecated` annotation on the command itself.
refs #262 
refs #263

deprecates integration with PHP Copy/Paste Detector (PHPCPD) library.

---

docs/CHANGELOG.md
src/Command/CopyPasteDetectorCommand.php
src/Command/InstallCommand.php

That way, both the web UI and the email from GitHub will show the recommendation about to move to the new "main" branch.
Also, unrelated, exclude some unreachable code from code coverage analysis.
Here there is an example to show how the annotation looks like (at the bottom):
https://github.com/stronk7/moodle-plugin-ci/actions/runs/7812729398
Note that an unrelated 2nd commit has been added about to try to keep Travis working, because it has started to fail recently (maybe they changed the PostgreSQL ports again, grrr).

Show a warning annotation when "master" branch usage is detected

---

.github/workflows/test.yml
src/Command/SelfUpdateCommand.php
tests/Command/SelfUpdateCommandTest.php

Note that only helper methods can be tested for that command, not the execution of the update itself (it has to happen within a PHAR). And it doesn't make much sense to start mocking lots of stuff for that.
Some integration tests @ CIS will be in charge of
covering the real execution instead. Coming soon.

Add tests to cover what is testable in SelfUpdate command

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/BehatCommand.php
tests/Command/BehatCommandTest.php
tests/Command/PHPUnitCommandTest.php
tests/MoodleTestCase.php

I've decided to remove the private properties because they were only used once, and now everything is encapsulated in the `getSeleniumImage` method.
Other than that, there isn't much more to the PR. It allows to configure the selenium image by setting `MOODLE_BEHAT_SELENIUM_IMAGE`, or specify it for each profile with `MOODLE_BEHAT_SELENIUM_CHROME_IMAGE` and `MOODLE_BEHAT_SELENIUM_FIREFOX_IMAGE`.
I also pondered whether to allow indicating only the browser version. For example, setting `MOODLE_BEHAT_CHROME_VERSION` or accepting `chrome:117` for the profile. But I wasn't convinced by that approach, so I ended up using this one that also allows customizing the image completely (for example, in case [you'd need to use seleniarm](https://github.com/moodlehq/moodle-docker/pull/250) or something …

Allow selenium image configuration

---

docs/CHANGELOG.md
res/template/config.php.txt
src/Bridge/MoodleConfig.php
tests/Bridge/MoodleConfigTest.php
tests/Fixture/example-config-with-chrome-capabilities.php
tests/Fixture/example-config-with-firefox-capabilities.php

I have tried using the [add-config](https://moodlehq.github.io/moodle-plugin-ci/AddExtraConfig.html) command to achieve this instead, but it seems like the Behat configuration is created in the `install` command so changes done afterwards are not applied. And if I try to use the `add-config` command before installing, I get an error.
So the only solution I've found is to modify `config.php.txt` before running the `install` command, but that's a bit fickle so it would be nice to have an idiomatic way to achieve it.

Configure browser capabilities

---

docs/CLI.md
src/Command/InstallCommand.php
src/Installer/InstallerFactory.php
src/Installer/VendorInstaller.php
tests/Fixture/plugin/package.json
tests/Installer/VendorInstallerTest.php

Add ignore-npm-dependencies setting

---

.travis.yml

Not much to say, let's verify that:
- The dev branch (main) works with its highest supported PHP version (8.3).
- The latest stable branch (403_STABLE) works with its highest supported PHP version (8.2).
- The oldest stable branch (39_STABLE) works with the lowest supported PHP version (7.4).
Link to travis PR run: https://app.travis-ci.com/github/moodlehq/moodle-plugin-ci/builds/269415755

Adjust the Travis tests to current php and moodle versions

---

.github/workflows/auto-author-assign.yml

Each time a PR is opened or reopened, the bot will assign the PR to the author.
(only if an assignee is not set)
You can see how it works @ https://github.com/stronk7/moodle-cs/pull/1 (both open and reopen)
Ciao :-)

For PRs, automatically set the author

---

.travis.dist.yml
docs/GHAFileExplained.md
docs/TravisFileExplained.md
gha.dist.yml

Better stop having the deprecated phpcpd command available in the dist and explain docs, so newcomers won't enable it by default. It's going to be removed in v5.
Part of #262, credit goes to @jrchamp

Remove phpcpd (deprecated) from dist and explain docs

---

docs/CHANGELOG.md
docs/GHAFileExplained.md
gha.dist.yml

Add GHA step to store Behat faildump as workflow artifact, so it can be [inspected](https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts).
This step will be run only if Behat step failed (see `if` statement). It also configured not to produce warning if files are not found (the cause of Behat error might be not the actual test scenario). Name is derived from the job matrix, it needs to be unique per job when matrix is used (artifact upload will fail on name conflict if more than 1 job will fail on Behat)
Demo (simplified for speed):
* Failed job: https://github.com/kabalin/moodle-format_flexsections/actions/runs/8307608604
* Succeeded job (no artifacts): https://github.com/kabalin/moodle-format_flexsections/actions/runs/8307723810
More info on upload …

Add step for Behat faildump storing as GHA artifact.

---

docs/CHANGELOG.md
docs/CLI.md
src/Command/PHPUnitCommand.php

This includes both the current default (when neither pcov or xdebug are available) and the explicit use of --coverage-phpdbg
Since PHP 8.0, phpdbg is causing all sort of problems and is not recommended. So it's time to deprecate it in order to proceed to remove it completely for moodle-plugin-ci 5.0.0.
Removal ref.: https://github.com/moodlehq/moodle-plugin-ci/issues/289
Fixes #213

Deprecate the phpdbg option for code coverage

---

.github/workflows/test.yml
tests/Fixture/moodle-local_ci/tests/lib_test.php

Just ensure that we fail on self integration tests (phpcs) warnings, so we can monitor the impact of every new moodle-cs release better.

Be stricter and don't allow warnings on phpcs tests

---

docs/CHANGELOG.md
src/Command/GruntCommand.php
tests/Command/GruntCommandTest.php

Limit stylelint tasks to plugin directory

---

.github/workflows/test.yml
.travis.yml
docs/MoodleApp.md
src/Bridge/MoodleConfig.php
src/Command/BehatCommand.php
src/Installer/MoodleAppInstaller.php

I'm opening this PR as a draft because until v4.4.0 of the app is released, these defaults don't work with the `moodlehq/moodleapp:latest-test` image, which is the default (they only work with `moodlehq/moodleapp:next-test`). But we can get the review started so that once 4.4.0 is released, we can merge this.
`moodle-docker` has a similar issue, but given that we explicitly support different versions, I've implemented an interim solution in https://github.com/moodlehq/moodle-docker/pull/281.
But for `moodle-plugin-ci`, I think it's fine just to support one version out of the box. And anyone can configure old versions if they want using other env variables (the documentation has also been updated).

Update App config defaults

---

src/Command/InstallCommand.php

Part of the tasks related to Moodle's `master` branch removal on 12 August 2024.

Remove the check and warning for master branch usage

---

docs/CHANGELOG.md
src/Installer/VendorInstaller.php

We should not rely on success exit status from nvm.sh loading.
Fixes #309

Fix nvm loading issue.

---

docs/CHANGELOG.md
src/Command/GruntCommand.php
tests/Command/GruntCommandTest.php

This change makes use of general stylelint task in grunt command, thus let grunt task to decide whether css or scss linter needs to be run (or both).
Also cleans up deprecated `stylelint:less` task (removed in 3.7 at MDL-64506) in a separate commit.
Fixes https://github.com/moodlehq/moodle-plugin-ci/issues/314

Use general stylelint task in grunt command

---

.github/workflows/test.yml
bin/validate-version
composer.lock
docs/CLI.md
src/Command/PHPUnitCommand.php

Bump a bunch of php dependencies to latest ones
Just update to current ones, automatically, without changing
any composer.json requirement.
Fixes #332 (and #333, just saw that one).
And, also, 3 more commits:
- Re-generates the CLI docs which features were changed by #320.  <-- (just a detail)
- Bump GHA to postgres 14, that is a requirement for Moodle 5.0.  <-- (self tests)
- Remove the PHPUnit --verbose option from Moodle >= 5.0 runs.  <-- (impacting!)

Bump php dependencies (and other minor tweaks)

---

gha.dist.yml

plugin installs against main branch of moodle are failing since the postgres 14 requirement has been integrated
```
Output:                                                                      
================                                                             
== Environment ==                                                            
!! database postgres (13.18 (Debian 13.18-1.pgdg120+1)) !!                   
[System] version 14 is required and you are running 13.18 -                  
```

Update to Postgres 14 as required by main

---

docs/CHANGELOG.md
src/Bridge/Moodle.php

`fetch_plugintypes` return signature was changed at [MDL-79843](https://tracker.moodle.org/browse/MDL-79843).

Fix getComponentInstallDirectory plugintypes retrieval issue.

---

.github/workflows/test.yml
.travis.dist.yml
.travis.yml
docs/CHANGELOG.md
docs/CLI.md
docs/TravisFileExplained.md
gha.dist.yml
res/template/config.php.txt
src/Command/BehatCommand.php
tests/Command/BehatCommandTest.php
tests/Fixture/example-config-with-chrome-capabilities.php
tests/Fixture/example-config-with-firefox-capabilities.php
tests/Fixture/example-config.php

1. E_STRICT does not have any meaning since PHP 8.0 and is officially deprecated in PHP 8.4 (Addresses https://github.com/moodlehq/moodle-plugin-ci/issues/344)
2. Add tests of moodle-plugin-ci on PHP 8.4
3. Add option --scss-deprecations for behat (Addresses https://github.com/moodlehq/moodle-plugin-ci/issues/343)
4. Bump PHP and postgres versions in Travis (not related to these issues but it was already failing)

Support PHP 8.4; Add option --scss-deprecations for behat

---

.github/workflows/test.yml
res/template/config.php.txt
tests/Fixture/example-config-with-chrome-capabilities.php
tests/Fixture/example-config-with-firefox-capabilities.php
tests/Fixture/example-config.php

1. E_STRICT does not have any meaning since PHP 8.0 and is officially deprecated in PHP 8.4 (Addresses #344)
2. Add tests of moodle-plugin-ci on PHP 8.4

Add support for PHP 8.4

---

bin/moodle-plugin-ci
docs/CHANGELOG.md

Note for reviewer: once approved, this needs to be merged without merge commit per [instruction](https://github.com/moodlehq/moodle-plugin-ci/blob/main/docs/ReleaseNewVersion.md).

Prepare for 4.5.7 release

---

.travis.dist.yml
README.md
bin/moodle-plugin-ci
docs/CHANGELOG.md
docs/index.md

This includes Travis CI deprecation notes, effectively preparing for its removal in 5.0.0 (#351).
I am not sure if we need to output deprecation message in the tool, in theory is it possible to check Travis specific environment var, and echo message, I could not find any standard warning CI output format like GH has, would simple echo be noticed? It is also not supposed to break existing CI setup, only if users bump install to `^5` something _may_ stop working.
Any thoughts @stronk7 @andrewnicols ?
**Note for reviewer**: once approved, this needs to be merged without merge commit (use "Rebase and merge" option per [instruction](https://github.com/moodlehq/moodle-plugin-ci/blob/main/docs/ReleaseNewVersion.md).

Prepare for 4.5.8 release
